### ISSUE TITLE
any example data for `fileName` and `charIndex`, thanks.

### ISSUE THREAD

**Issue by liamxg** [supramap/transmission_graphs#2]
fileName <- readline(prompt = "Type in the full path to the nexus file you want to read in: ")
nexusTree2 <- read.nexus(fileName)
nexusData <- getMetadata(fileName)

charIndex <- readline(prompt ="Type the number equivalent to the character state index of the nexus file you want to build the network from: ")
characterIndex <- as.numeric(charIndex) #Transforms the input from string to numeric so it can be loaded on metadataRef
rootedTree <- nexusTree2

**Comment by liamxg** [comment]
@colbyford @supramap

**Comment by colbyford** [comment]
This is a very early (and outdated) version of the StrainHub software. Please use the current code from this repo: https://github.com/abschneider/StrainHub

Sample data: https://github.com/abschneider/StrainHub/tree/master/data/parsimonious/chikv

**Comment by liamxg** [comment]
@colbyford thanks, you are so kind.
